# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  node: circleci/node@4.1.0
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: /home/circleci/project/TDD_Assignment
          cache-path: /home/circleci/project/TDD_Assignment
          override-ci-command: npm install mocha && alias mocha='./node_modules/.bin/_mocha' && npm install
      - run:
          command: npm start
          background: true
          working_dir: /home/circleci/project/TDD_Assignment
      - run: sleep 5
      - run: 
          command: npm run test
          working_dir: /home/circleci/project/TDD_Assignment
