# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  node: circleci/node@4.1.0
jobs:
  build:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/TDD_Assignment
          override-ci-command: npm install
      - run:
          command: npm start
          background: true
      - run: sleep 5
      - run: npm run test